project:
  type: website
  output-dir: docs

website:
  title: "Anish Rao"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        menu:
          - text: "--- Business Intelligence ---"
          - href: projects/data-viz/viz_index.qmd
            text: BI & Data Visualization
          - href: projects/taxi-dw/taxi_index.qmd
            text: NYC Taxi Data Warehouse
          - text: "--- Machine Learning & AI ---"
          - href: projects/churn-prediction/churn_index.qmd
            text: Customer Churn (Explainable AI)
          - href: projects/mlpr-1/ner_index.qmd
            text: Medical Named Entity Recognition
          - href: projects/mlpr-2/anomaly_index.qmd
            text: Anomaly Detection in Time Series
          - text: "--- Data Science & Mining ---"
          - href: projects/sentiment-analysis/sentiment_index.qmd
            text: Sentiment Analysis
          - href: projects/data-mining/mining_index.qmd
            text: Data & Network Mining
          # - text: "--- Others ---"
          # - href: projects/statistics/stats_index.qmd
          #   text: Statistical Analysis Q&A

format:
  html:
    theme: cosmo
    css: styles.css
    bootstrap-icons: true
    toc: true